"""add_created_at_to_orders

Revision ID: 67fa0149dc66
Revises: c0d6768df1f0
Create Date: 2026-03-20 22:53:28.618189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fa0149dc66'
down_revision: Union[str, Sequence[str], None] = 'c0d6768df1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
